name: Release Cargo

permissions:
  contents: write

on:
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN} -p arrow-message-derive
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN} -p arrow-message
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}